### PR TITLE
Prepare package for pip upload

### PR DESCRIPTION
**Pull request by davidwickerhf**
HypeAPI is a great package!
I wish I could install it directly via python's pip.
So I wrapped the banking modules (banking, hype and timpay) into a banking package.
The modules all still work the same and imports remain almost unvaried.

### CODE REVIEW

**Comment by jacopo-j** [comment]
Hi, your changes are mostly fine with me, however I'm not sure about using "banking" as package name. It sounds a bit too generic for this project, which is specifically about HYPE and TIM Pay

**Comment by davidwickerhf** [comment]
@jacopo-j  I understand
I thought of naming it banking as it generalizes Hype and TimPay and leaves room for additions in the future (I'll likely try to implement the APIs for Bunq & N26 in the repo's fork).
But yeah, it's your project, and the package name is just more of a 'formality', so I can change it back to HypeAPI or anything else if you have another suggestion

**Comment by jacopo-j** [comment]
Okay, the name makes sense if you want to integrate more banks later. Anyway I suggest that we keep the fork separate since I see the project is quickly becoming more complex and I likely won't have the time to follow its development. If this is fine for you I'll cose this PR without merging, and you can continue to work on your fork (and eventually push it to PIP).

**Comment by davidwickerhf** [comment]
Alright, no problem
Thank you for your help and for starting this project!

**Pull request closed without merging**
